---
- name: Install Docker
  hosts: all 
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker 
        update_cache: yes
        state: present
    - name: Start docker daemon
      systemd:
        name: docker
        state: started 

- name: Create new linux user
  hosts:  all 
  become: yes 
  vars_files:
    - project-vars
  tasks:
    - name: Create new linux user 
      user:
        name: barry
        groups: "{{ user_groups }}"
   
- name: Install Docker-compose
  hosts: all
  become: yes 
  become_user: barry
  tasks:
    - name: Create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ remote_arch.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x

- name: Start docker containers
  hosts: all
  become: yes 
  become_user: barry
  vars_files:
    - project-vars 
  tasks:
    - name: Copy docker compose
      copy:
        src: /Users/Barry/java-maven-app/docker-compose.yaml
        dest: /home/barry/docker-compose.yaml
    - name: Docker login
      docker_login:
        username: alkerix
        password: "{{docker_password}}"
    - name: Start containers from compose 
      community.docker.docker_compose_v2:
        project_src: /home/barry
      environment:
        IMAGE: "{{ docker_image }}"
      