version: '3'

services:
  java-app:
    image: alkerix/java-maven-app-1.0
    container_name: my-java-app
    ports:
      - "8080:8080"
    environment:
      - DB_USER=user
      - DB_PWD=pass
      - DB_SERVER=mysql
      - DB_NAME=my-app-db
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my-app-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    ports:
      - "8083:80"

volumes:
  mysql-data:
    driver: local